### ISSUE TITLE
Not able to run the executable 

### ISSUE THREAD

**Issue by Tekh-ops** [MathisBullinger/aurora-cpp#1]
OS : macOS Monterey 12.0.1 (21A559)
Error : 
couldn't open file: cube.obj
couldn't open file: teapot2.obj
couldn't open file: porcelain.bmp
[OpenGL error]: (0x501): glTexImage2D(type, 0, GL_RGB, width, height, 0, GL_BGR, GL_UNSIGNED_BYTE, data) in /Users/mac/temp/aurora-cpp/src/renderer/texture.cpp, line 30
[1]    3695 trace trap  ./build/aurora

**Comment by MathisBullinger** [comment]
I haven't included any static assets in the repo, so if you want to run this you'll need to supply textures and meshes yourself. In this case, the required files would be `resources/textures/procelain.bmp`; `back.bmp`, `bottom.bmp`, `front.bmp`, `left.bmp`, `right.bmp`, and `top.bmp` in `resources/textures/skybox` for the skybox; and a mesh as obj file including vertex positions, normals, and UVs at `resources/meshes/teapot2.obj`.

But honestly, this repo is just me messing around with graphics programming for my personal education/entertainment. So I won't make any extra effort to ensure anyone else can build and run this and wouldn't recommend anyone do.
